# Generated by Django 6.0.5 on 2026-05-15 13:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', ckeditor.fields.RichTextField()),
                ('eligibility', ckeditor.fields.RichTextField()),
                ('age_limit', models.CharField(max_length=255)),
                ('total_posts', models.CharField(max_length=255)),
                ('application_fee', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('important_dates', ckeditor.fields.RichTextField()),
                ('selection_process', ckeditor.fields.RichTextField()),
                ('how_to_apply', ckeditor.fields.RichTextField()),
                ('apply_link', models.URLField()),
                ('official_website', models.URLField()),
                ('official_notification_pdf', models.FileField(blank=True, null=True, upload_to='jobs/pdfs/')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='jobs/images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
