# Generated by Django 6.0.5 on 2026-07-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='eligibility',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='how_to_apply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='important_dates',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='selection_process',
            field=models.TextField(),
        ),
    ]
